/* eslint-disable import/prefer-default-export */

export const NAME_LIMIT = 50;
export const DESCRIPTION_LIMIT = 2000;

export const RFR_HOME = 'RFR_HOME';
export const RFR_PROJECT_STEP = 'RFR_PROJECT_STEP';
export const RFR_JUMP_TO_STEP_BY_STEP_RANK = 'RFR_JUMP_TO_STEP_BY_STEP_RANK';
export const RFR_PROJECT_STEP_THUNK_END = 'RFR_PROJECT_STEP_THUNK_END';
export const RFR_LOGOUT = 'RFR_LOGOUT';
export const RFR_CREATE_PROJECT = 'RFR_CREATE_PROJECT';
export const RFR_NOT_FOUND = 'RFR_NOT_FOUND';
export const RFR_PROJECT_ROOT = 'RFR_PROJECT_ROOT';
export const RFR_NO_STEPS = 'RFR_NO_STEPS';
export const RFR_NO_STEPS_THUNK_END = 'RFR_NO_STEPS_THUNK_END';
export const RFR_PROJECT_REPORT = 'RFR_PROJECT_REPORT';

export const OPEN_NOT_FOUND_DIALOG = 'OPEN_NOT_FOUND_DIALOG';
export const CLOSE_NOT_FOUND_DIALOG = 'CLOSE_NOT_FOUND_DIALOG';

export const UPDATE_ADD_STEP_DIALOG = 'UPDATE_ADD_STEP_DIALOG';
export const UPDATE_STEP_JUST_CHANGED_STATUS = 'UPDATE_STEP_JUST_CHANGED_STATUS';

export const UPDATE_DIALOG = 'UPDATE_DIALOG';

export const PREV_STEP = 'PREV_STEP';
export const NEXT_STEP = 'NEXT_STEP';
export const SUBMIT_STEP = 'SUBMIT_STEP';
export const ADD_STEP = 'ADD_STEP';
export const ADD_RECIPE_STEPS = 'ADD_RECIPE_STEPS';
export const REMOVE_STEP = 'REMOVE_STEP';
export const REMOVE_ALL_STEPS = 'REMOVE_ALL_STEPS';
export const REORDER_STEP = 'REORDER_STEP';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const MODIFY_PROJECT = 'MODIFY_PROJECT';
export const UPDATE_CURRENT_STEP = 'UPDATE_CURRENT_STEP';
export const QUERY_BACKEND = 'QUERY_BACKEND';
export const INTERCEPT_STEP = 'INTERCEPT_STEP';
export const RESET_STEP = 'RESET_STEP';
export const RESET_STEP_RECURSIVELY = 'RESET_STEP_RECURSIVELY';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const COMPONENT_SET_STATE = 'COMPONENT_SET_STATE';
export const CLEAR_ERRORS_FOR_STEP = 'CLEAR_ERRORS_FOR_STEP';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const SAVE_CURRENT_PIPELINE_AS_RECIPE = 'SAVE_CURRENT_PIPELINE_AS_RECIPE';

export const GLOBAL_ERROR = 'GLOBAL_ERROR';
export const GLOBAL_DIALOG = 'GLOBAL_DIALOG';
export const DISMISS_GLOBAL_DIALOG = 'DISMISS_GLOBAL_DIALOG';
export const DYNAMIC_DISPATCH_ACTION = 'DYNAMIC_DISPATCH_ACTION';
export const UPDATE_WELCOME_DIALOG = 'UPDATE_WELCOME_DIALOG';
