main:
	typescript-json-schema --required --noExtraProps types/index.d.ts IRecipeSpec > jsonSchemas/IRecipeSpec.json
	typescript-json-schema --required --noExtraProps types/index.d.ts IGboxSpec > jsonSchemas/IGboxSpec.json
	typescript-json-schema --required --noExtraProps types/index.d.ts IPackageSpec > jsonSchemas/IPackageSpec.json
