# this name will be displayed in the package installation
id: Granatum2 Multi-Tool (written in R/Python)

# this meta field provides the default meta for all gboxes
# for example, if `./yamls/DifferentialExpression.yaml` doesn't
# have a "maintainer" field in it, then the "maintainer" defaults
# to the one here.
meta:
  maintainer:
    name: Thomas K. Wolfgruber
    email: twolfgruber@cc.hawaii.edu

# an array of all the yaml specs for the gboxes
gboxes:
  - ./yamls/DifferentialExpression.yaml
  - ./yamls/FGSEA.yaml
  - ./yamls/GeneFiltering.yaml
  - ./yamls/MonoclePseudotime.yaml
  - ./yamls/Normalization.yaml
  - ./yamls/PPI.yaml

buildCommand: 'cd docker && make'
