meta:
  title: "Pseudo-time plot"
  subtitle: "Pseudo-time series construction from Monocle"
  maintainer:
    name: "Thomas K. Wolfgruber"
    email: "twolfgruber@cc.hawaii.edu"
  citation:
    bibtex: >
      "@article{Qiu2017,doi = {10.1101/110668},url =
      {https://doi.org/10.1101/110668}, year  = {2017},month = {feb},publisher =
      {Cold Spring Harbor Laboratory},author = {Xiaojie Qiu and Qi Mao and Ying Tang
      and Li Wang and Raghav Chawla and Hannah Pliner and Cole Trapnell},title =
      {Reversed graph embedding resolves complex single-cell developmental
      trajectories}}"
  description: >
      "This step orders cells in pseudo-time by learning from single-cell assay data
      using Reversed Graph Embedding. The position of each cell in the resulting plot
      is expected to reflect its relative biological state along one or more
      potential cell trajectories."
endpoints:
  backend:
    type: "docker"
    image: "granatum2_multi-tool_tw"
    cmd: "Rscript ./pseudo-time.R"
frontend:
  imports:
    - kind: "assay"
      injectInto: "assay"
      label: "The assay that contains the matrix to use for pseudo-time cell ordering" 
  args:
    - type: "number"
      name: "seed"
      label: "Random seed"
      default: 96813
