#suppressPackageStartupMessages({
#  library(monocle)
#  library(jsonlite)
#  library(ggplot2)
#  library(base64enc)
#})
message("Usage: cat my_in.json | docker run -i --rm my_image ./my_command > my_out.json")
message("my_command:")
message("\trun_psuedo-time.sh (***warning: IO needs reformatting***)")
message("\trun_normalization.sh (***warning: IO needs reformatting***)")
message("\trun_de_dyn.sh")
message("\trun_de.sh")
message("Description:")
message("\trun_de_dyn.sh: results and exports for dynamic UI.")
message("\trun_de.sh: results from differential expression analysis.")
message("\trun_filter_genes.sh: gene filtering by expression level and dispersion.")
message("\trun_enrichment.sh: get enriched KEGG/GO pathways/terms from differentially expressed genes.")
#sessionInfo()
